" =======================================
"                   VIM
" Author: Rex Tsou<akccakccwww@gmail.com>
" =======================================
" ## General {{{
set history=500
set shell=$SHELL
set ttyfast

if has('macunix')
  set clipboard=unnamed " use the OS clipboard by default
endif

if !has('nvim')
  set nocompatible
  if &term =~ '^screen\|^tmux' && exists('$TMUX')
    if &term =~ '256color'
      set term=xtem-256color
    else
      set term=xterm
    endif
  endif
  if &term =~ '256color'
    set t_ut=
  endif
  if exists('$TMUX')
    set t_8f=[38;2;%lu;%lu;%lum
    set t_8b=[48;2;%lu;%lu;%lum
  endif
endif

if has('nvim')
  let g:python3_host_prog = '/usr/bin/python3'
endif
" }}}

" ## Map leader {{{
let mapleader = ','
let maplocalleader = ','
let g:mapleader = ','
let g:maplocalleader = ','
" }}}

" ## Plugin manager (vim-plug) {{{
call plug#begin('~/.vim/plugged')

" Plug 'Townk/vim-autoclose'
" Plug 'altercation/vim-colors-solarized' "colorscheme
" Plug 'ervandew/supertab',
" Plug 'joshdick/onedark.vim' " colorscheme
Plug 'Chiel92/vim-autoformat'
Plug 'SirVer/ultisnips'
Plug 'Valloric/YouCompleteMe'
Plug 'airblade/vim-gitgutter'
Plug 'cakebaker/scss-syntax.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'digitaltoad/vim-pug', { 'for': 'pug' }
Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'honza/vim-snippets'
Plug 'iamcco/markdown-preview.vim'
Plug 'jacoborus/tender' " colorscheme
Plug 'jlanzarotta/bufexplorer'
Plug 'junegunn/gv.vim' " Git commit browser
Plug 'junegunn/vim-easy-align'
Plug 'lilydjwg/colorizer'
Plug 'majutsushi/tagbar'
Plug 'maksimr/vim-jsbeautify'
Plug 'mattn/emmet-vim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'pangloss/vim-javascript'
Plug 'plasticboy/vim-markdown'
Plug 'posva/vim-vue'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'tomasiser/vim-code-dark' " colorscheme
Plug 'tpope/vim-fugitive' " Git wrapper
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junkblocker/patchreview-vim' "GitHub PR Code Review
Plug 'codegram/vim-codereview' " GitHub PR Code Review
Plug 'vim-syntastic/syntastic' " syntax checking

call plug#end()            " required
"
" Brief help
" :PlugInstall      - Install plugins
" :PlugUpdate       - Install or update plugins
" :PlugClean[!]     - Remove unused directories (bang version will clean without prompt)
" :PlugUpgrade      - Upgrade vim-plug itself
" :PlugStatus       - Check the status of plugins
" :PlugDiff         - Examine changes from the previous update and the pending changes
" :PlugSnapshot[!] [output path] - Generate script for restoring the current snapshot of the plugins
"
" see https://github.com/junegunn/vim-plug for more informations
" =====
" Plugins settings and mappings

" --- NERDTree --- {{{
noremap <F5> :NERDTreeToggle<CR> " toggle nerdtree display
nnoremap <C-b> :NERDTreeToggle<CR>
nnoremap ,t :NERDTreeFind<CR> " open nerdtree with the current file selected

" don't show these file types
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
" }}}

" --- NERD Commenter --- {{{
let g:NERDSpaceDelims = 1
let g:NERDRemoveExtraSpaces = 1
" }}}

" --- Syntastic --- {{{
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"  }}}

" --- editorconfig plugin --- {{{
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
" }}}

" --- *.vue file syntax --- {{{
autocmd FileType vue syntax sync fromstart
" }}}

" --- Autoformat --- {{{
" (,FF)
nnoremap <Leader>FF :Autoformat<CR>
" }}}

" --- BufExplorer --- {{{
let g:bufExplorerSortBy = 'name'
let g:bufExplorerShowRelativePath = 1
let g:bufExplorerShowNoname = 1
" }}}

" --- YouCompleteMe --- {{{
" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'
" }}}

" --- UltiSnips --- {{{
let g:UltiSnipsExpandTrigger = "<Tab>"
let g:UltiSnipsJumpForwardTrigger = "<Tab>"
let g:UltiSnipsJumpBackwardTribber = "<s-Tab>"
" }}}

" --- Emmet --- {{{
" let g:user_emmet_leader_key='<C-y>'
" let g:user_emmet_mode='in' " only enable in Input/Normal mode
let g:user_emmet_install_global = 0 " enable just for HTML/CSS
autocmd filetype html,css,scss,pug EmmetInstall
"autocmd filetype *html* inoremap <A-/> <C-y>/
"autocmd filetype *html* vnoremap <A-/> <C-y>/
" }}}

" --- Tagbar --- {{{
nnoremap <F8> :Tagbar<CR>
"  }}}

" --- EasyAlign --- {{{
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
" }}}

" --- CtrlP --- {{{
" file finder mapping
let g:ctrlp_map = '<C-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
" tags (symbols) in current file finder mapping
nnoremap ,g :CtrlPBufTag<CR>
" tags (symbols) in all files finder mapping
nnoremap ,G :CtrlPBufTagAll<CR>
" general code finder in all files mapping
nnoremap ,f :CtrlPLine<CR>
" recent files finder mapping
nnoremap ,m :CtrlPMRUFiles<CR>
" commands finder mapping
nnoremap ,c :CtrlPCmdPalette<CR>
" to be able to call CtrlP with default search text
function! CtrlPWithSearchText(search_text, ctrlp_command_end)
  execute ':CtrlP' . a:ctrlp_command_end
  call feedkeys(a:search_text)
endfunction
" same as previous mappings, but calling with current word as default text
nmap ,wg :call CtrlPWithSearchText(expand('<cword>'), 'BufTag')<CR>
nmap ,wG :call CtrlPWithSearchText(expand('<cword>'), 'BufTagAll')<CR>
nmap ,wf :call CtrlPWithSearchText(expand('<cword>'), 'Line')<CR>
nmap ,we :call CtrlPWithSearchText(expand('<cword>'), '')<CR>
nmap ,pe :call CtrlPWithSearchText(expand('<cfile>'), '')<CR>
nmap ,wm :call CtrlPWithSearchText(expand('<cword>'), 'MRUFiles')<CR>
nmap ,wc :call CtrlPWithSearchText(expand('<cword>'), 'CmdPalette')<CR>
" don't change working directory
let g:ctrlp_working_path_mode = 0
" ignore these files and folders on file finder
set wildignore+=*/tmp/*,*.so*,*.swp,*.zip " macOS/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe " Windows
let g:ctrlp_custom_ignore = {
      \ 'dir':  '\v[\/](\.git|\.hg|\.svn|node_modules)$',
      \ 'file': '\v\.(pyc|pyo|exe|so|dll)$',
      \ }
" }}}

" --- Indent Guildes --- {{{
let g:indent_guides_start_level = 2
let g:indent_guides_auto_colors = 0
let g:indent_guides_default_mapping = 0 " (toggle IndentGuides with <Leader>ig)
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=black ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=233
" }}}

" --- Airline --- {{{
let g:airline_powerline_fonts = 0
" set airline theme
let g:airline_theme = 'tender'
"let g:airline_theme = 'bubblegum'
let g:airline#extensions#whitespace#enabled = 0

"enable tender airline theme
let g:tender_airline = 1
" }}}
" }}}

" ## Wildmode {{{
" autocompletion of files and commands behaves like shell
" (complete only the common part, list the options that match)
set wildmode=list:longest
" }}}

" ## Tabs, Spaces and Indent handling {{{

set autoindent " auto indent
" set expandtab " expand tab to be space
set noexpandtab
set tabstop=2 " make Tabs display as wide as 2 Spaces
set shiftwidth=2 " 2 columns text is indented with the reindent operations (<< and >>)
set softtabstop=2 " 2 columns vim uses when hitting Tab in insert mode
set smarttab

" tab length exceptions on some file types
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmldjango setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType php setlocal shiftwidth=2 tabstop=2 softtabstop=2
" }}}

" ## Better Backup, Swap and Undo storage {{{
set directory=~/.vim/dirs/tmp     " directory to place swap files in
set backup                        " make backup files
set backupdir=~/.vim/dirs/backups " where to put backup files
set undofile                      " persistent undos - undo after you re-open the file
set undodir=~/.vim/dirs/undos
set viminfo+=n~/.vim/dirs/viminfo
" store yankring history file there too
let g:yankring_history_dir = '~/.vim/dirs/'

" create needed directories if they don't exist
if !isdirectory(&backupdir)
  call mkdir(&backupdir, "p")
endif
if !isdirectory(&directory)
  call mkdir(&directory, "p")
endif
if !isdirectory(&undodir)
  call mkdir(&undodir, "p")
endif
" }}}

" ## UI settings {{{
set number
set showmatch
set scrolloff=3 " when scrolling, keep cursor 3 lines away from screen border
set timeout
set ttimeoutlen=10
set virtualedit=block
set nolazyredraw
set whichwrap+=<,>,[,]
set nostartofline
set autoread " auto read when a file is changed from the outside
set backspace=indent,eol,start
set wrap " wrap lines
set mouse=a
set cursorline " highlight current line
set updatetime=100

" --- Colorscheme --- {{{
syntax on
set bg=dark

" use 256 colors when possible
if (&term =~? 'mlterm\|xterm\|xterm-256\|screen-256') || has('nvim')
  let &t_Co = 256
  let g:solarized_termtrans = 1 " get rid of the grey background"
  " colorscheme solarized
  " colorscheme onedark
  colorscheme codedark
else
  colorscheme delek
endif

if has('gui_running')
  " colorscheme evening
  colorscheme codedark
  set guifont=Consolas:h18 " for Windows
  set guifont=monospace\ 18 " for Linux
  set guifont=Monaco:h18 " for macOS
endif

hi Folded ctermfg=59
" }}}

" --- natural split opening --- {{{
set splitbelow
set splitright
"  }}}

" --- let alt key can be mapped as <M-*> --- {{{
" set winaltkeys=no
" for i in range(65,90) + range(97,122)
  " let c = nr2char(i)
  " exec "map \e".c." <M-".c.">"
  " exec "map! \e".c." <M-".c.">"
" endfor
" }}}

" --- sound on errors --- {{{
set novisualbell
set noerrorbells
" }}}

" --- search --- {{{
set hlsearch " highlighted search results
set incsearch " incremental search
set magic
set ignorecase
set smartcase
" }}}

" --- folding --- {{{
set foldenable
set foldlevelstart=3
set foldmethod=indent " syntax
" }}}

" --- status bar  --- {{{
set laststatus=2
set cmdheight=1
set showcmd
set noshowmode
set ruler
" }}}


" }}}

" ## Fonts, Encoding {{{
" set encoding
set fileencoding=utf-8
set encoding=utf-8
" let $LANG="zh_TW.UTF-8"
" set langmenu=zh_tw.utf-8

" reload gVim menu with UTF-8 encoding
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" fileformats
set fo+=Mm " for multi byte character
set fo+=crql
set fo-=t
set ffs=unix,dos,mac
" }}}

" ## Key Mappings {{{

" edit .vimrc
nnoremap <silent> <leader>ee :tabe ~/.vimrc<CR>

" open a new tab
nnoremap <C-n> :tabnew<CR>

" switch to next tab
noremap <Leader>n :tabnext<CR>
noremap <Leader>p :tabprevious<CR>

" split window
" horizontal, same as <C-w>v
nnoremap <C-\> :vsp<CR>

" split window navigations
nnoremap <C-Left> <C-w>h
nnoremap <C-Down> <C-w>j
nnoremap <C-Up> <C-w>k
nnoremap <C-Right> <C-w>l

" switch between vertical/horizontal split
nnoremap <Leader>E :windo wincmd K<CR>
nnoremap <Leader>I :windo wincmd H<CR>

" no highlight search result
nnoremap <Leader>/ :nohl<CR>

" toggle wrap
noremap <F2> :set wrap! wrap?<CR>

" increase and decrease number under the cursor
nnoremap + <C-a>
nnoremap - <C-x>

" move text with CTRL+[jk]
nnoremap <C-j> :m+<CR>:echo "move line down"<CR>
nnoremap <C-k> :m-2<CR>:echo "move line up"<CR>
" inoremap <C-j> <Esc>:m+<CR>:echo "move line down"<CR>gi
" inoremap <C-k> <Esc>:m-2<CR>:echo "move line up"<CR>gi
vnoremap <C-j> :m'>+<CR>:echo "move block down"<CR>
vnoremap <C-k> :m'<-2<CR>:echo "move block up"<CR>

" avoid the escape key
nnoremap <C-e> <Esc>
inoremap <C-e> <Esc>
vnoremap <C-e> <Esc>
snoremap <C-e> <Esc>
inoremap jj <Esc>

" }}}

" ## Functions {{{

" Strip trailing whitespace (,ss)
function! StripWhitespace()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  :%s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfunction
noremap <Leader>ss :call StripWhitespace()<CR>

" Save a file as root (,WW)
noremap <Leader>WW :w !sudo tee % > /dev/null<CR>

" }}}

" --- Arrow-keys error signal workaround --- {{{
" enter insert-mode, press <C-v> and then press arrow-keys to get the signals
" nnoremap <silent> <Esc>OA <Up>
" nnoremap <silent> <Esc>OB <Down>
" nnoremap <silent> <Esc>OC <Right>
" nnoremap <silent> <Esc>OD <Left>
" vnoremap <silent> <Esc>OA <Up>
" vnoremap <silent> <Esc>OB <Down>
" vnoremap <silent> <Esc>OC <Right>
" vnoremap <silent> <Esc>OD <Left>

" }}}

" vim:fdm=marker:foldlevel=0

